name: trage
description: The $trage game.
version: 1.0.0
repository: https://github.com/circloid/trage

environment:
  sdk: ^3.8.1

executables:
  trage: bin

dependencies:
  gesso: ^1.0.3
  udp: ^5.0.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
